# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.10.2"

package:
  name: bpf-linker
  version: ${{ version }}

source:
  url: https://github.com/aya-rs/bpf-linker/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c4e99d548b6a0d90f6ef35acb348cf4b8944ff4ba62b2795aa688b3178d82141

build:
  number: 0
  # this (somewhat surprisingly) works on `osx-64`, but (not unsurprisingly) fails on `win-64`:
  #
  #   error[E0433]: failed to resolve: could not find `unix` in `os`
  #
  skip: win
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    content:
      - cargo install --no-track --locked --path=. --profile=release --root="${{ PREFIX }}"
      - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
  host:
    - llvmdev
  run:
    - llvmdev

tests:
  - script:
      - bpf-linker --version
      - bpf-linker --help

about:
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  homepage: https://github.com/aya-rs/bpf-linker
  summary: Simple BPF static linker

extra:
  recipe-maintainers:
    - bollwyvl
